---
resources:
- name: git-resource
  type: git
  source:
    uri: ((git-url))
- name: ((pack-builder-image)):((pack-builder-tag))
  type: docker-image
  source:
    repository: ((pack-builder-image))
    version: ((pack-builder-tag))
- name: pack-goflake
  type: pack-image-resource
  source:
    repository: ((repository))
    username: ((docker-hub-username))
    password: ((docker-hub-password))

resource_types:
- name: pack-image-resource
  type: docker-image
  privileged: true
  source:
    repository: bstick12/pack-concourse-resource
    version: latest

jobs:
- name: build-goflake-image
  plan:
  - get: git-resource
    trigger: true
  - get: ((pack-builder-image)):((pack-builder-tag))
    trigger: true
    params: {skip_download: true}
  - put: pack-goflake
    params:
      build: git-resource
      builder: ((pack-builder-image)):((pack-builder-tag))
